---
- hosts: windows
  name: "STOP/START Serviço"
  vars:
   service: Spooler

  tasks: 
   - name: 'Parar serviço'
     win_service:
      name: "{{ service }}"
      start_mode: auto
      state: stopped

   - name: 'Iniciar serviço'
     win_service:
      name: "{{ service }}"
      state: started


