---
- hosts: windows
  name: "STOP/START Serviço"
  vars:
   service: Spooler
   
   ############## SERVER:  SERVICOS-<bandeira>01 ######################
   # 
   # 
   # GPA.Servicos.Loja.EnviarPedidosDominioERP
   # GPA.Servicos.Loja.RecuperarTracking
   # GPA.Servicos.Loja.RecuperarTrackingMainframe
   # GPA.Servicos.Loja.AtualizarBannerCarrossel
   # GPA.Servicos.Loja.EnviarEmail
   # GPA.Servicos.Loja.EnviarEmailAviseMe
   # GPA.Servicos.Loja.EnviarSms
   # GPA.Servicos.Loja.EnviarPedidoMarketPlace
   # GPA.Servicos.Loja.EnviarLiberarEntregas
   # GPA.Servicos.Loja.AtualizarStatusEstornoPagamento
   # GPA.Servicos.Loja.AtualizarVales
   # GPA.Servicos.Loja.ProcessarValeTransacao
   # Cnova.IntegrationMktp.Host.IntegracaoCompraStatus
   # GPA.Servicos.Loja.EnviarProxyPagamento.0
   # GPA.Servicos.Loja.EnviarProxyPagamento.1
   # GPA.Servicos.Loja.EnviarProxyPagamento.2
   # GPA.Servicos.Loja.EnviarProxyPagamento.3
   # GPA.Servicos.Loja.EnviarProxyPagamento.4
   # GPA.Servicos.Loja.EnviarProxyPagamento.5
   # GPA.Servicos.Loja.EnviarProxyPagamento.6
   # GPA.Servicos.Loja.EnviarProxyPagamento.7
   # GPA.Servicos.Loja.EnviarProxyPagamento.8
   # GPA.Servicos.Loja.EnviarProxyPagamento.9
   # GPA.Servicos.Loja.EnviarProxyPagamento3DS
   #
   #
   ####################################################################
   
  tasks: 
   - name: 'Parar serviço'
     win_service:
      name: "{{ service }}"
      start_mode: auto
      state: stopped

   - name: 'Iniciar serviço'
     win_service:
      name: "{{ service }}"
      state: started


